//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int jobID { get; set; }
        public string jobName { get; set; }
        public string salary { get; set; }
        public string description { get; set; }
        public string required { get; set; }
        public string deadline { get; set; }
        public string domainID { get; set; }
        public string domainName { get; set; }
        public Nullable<int> number { get; set; }
        public string companyID { get; set; }
        public string cityID { get; set; }
        public string cityName { get; set; }
        public string positionName { get; set; }
        public string positionID { get; set; }
        public string timeID { get; set; }
        public string timeInfo { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Company Company { get; set; }
        public virtual Place Place { get; set; }
        public virtual Position Position { get; set; }
        public virtual Time Time { get; set; }
    }
}
