//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Place
    {
        public Place()
        {
            this.Jobs = new HashSet<Job>();
        }
    
        public string placeID { get; set; }
        public string placeName { get; set; }
    
        public virtual ICollection<Job> Jobs { get; set; }
    }
}
