//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebHotelv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Domain
    {
        public Domain()
        {
            this.Jobs = new HashSet<Job>();
        }
    
        public int domainID { get; set; }
        public string domainName { get; set; }
    
        public virtual ICollection<Job> Jobs { get; set; }
    }
}
