//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebHotelv2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Time
    {
        public Time()
        {
            this.Jobs = new HashSet<Job>();
        }
    
        public int timeID { get; set; }
        public string timeInfo { get; set; }
    
        public virtual ICollection<Job> Jobs { get; set; }
    }
}
